export const CERTIFICATE_TYPES = {
  BAPTISM: "BAPTISM_CERTIFICATE",
  MARRIAGE: "MARRIAGE_CERTIFICATE",
  DEATH: "DEATH_CERTIFICATE",
  FAMILY: "FAMILY_CERTIFICATE",
} as const;

export const ALLOWED_CERTIFICATE_TYPES = Object.values(
  CERTIFICATE_TYPES
);